### ISSUE TITLE
Record skip & only as meta data

### ISSUE THREAD

**Issue by michaeljones** [pausan/mocha-list-tests#6]
At the moment the code treats "standard", skip & only as the same. Would you consider extending the functionality to record the skip & only usage as meta data that is output in the final JSON? I think it would make sense but it depends if it keeps with your vision for the project.

Maybe the tree could go deeper to:

```json
    "tree": {
        "Example suite name": {
            ":before": {
                "file": "path/to/my/file.test.js",
                "line": 18
            },
            "example test name": {
                "file": "path/to/my/file.test.js",
                "line": 32,
                "skip": true,
                "only": false
            },
            "example test name 2": {
                "file": "path/to/my/file.test.js",
                "line": 32,
                "skip": false,
                "only": true
            }
        },
        ...
```
Or something like that.

**Comment by pausan** [comment]
I've extended the functionality so on the result object there is now a property called "extended_tree" so that everything remains backwards compatible, and still, using this "extended_tree" you'll have more information about tests, ...

However, the structure of the tree is slightly different. Now all non-leaf tests/describe/suite have a **children** attribute. That way you can also get the file/line/type of each node in the tree.

**Comment by michaeljones** [comment]
That's great. Thank you so much. I'm glad you felt it was a suitable idea. This will be really helpful.

**Comment by pausan** [comment]
Glad to hear. I thought you had a good point and it was a good idea to have more granular information. I didn't want to break backwards compatibility either, and that's why I added an extra parameter. Probably you have already noticed but I've also updated the README.md with an output example (for people to get an idea on what is returned by this library).
